<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="3" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="237087" started-at="2019-06-10T10:14:08Z" finished-at="2019-06-10T10:18:05Z">
    <groups>
    </groups>
    <test name="Validate login functionality" duration-ms="135402" started-at="2019-06-10T10:14:08Z" finished-at="2019-06-10T10:16:23Z">
      <class name="tests.LoginTest">
        <test-method status="PASS" signature="openBrowser()[pri:0, instance:tests.LoginTest@77fbd92c]" name="openBrowser" is-config="true" duration-ms="6097" started-at="2019-06-10T10:14:08Z" finished-at="2019-06-10T10:14:14Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openBrowser -->
        <test-method status="PASS" signature="verifyInvalidLoginValidationMessage()[pri:0, instance:tests.LoginTest@77fbd92c]" name="verifyInvalidLoginValidationMessage" duration-ms="128458" started-at="2019-06-10T10:14:14Z" finished-at="2019-06-10T10:16:22Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyInvalidLoginValidationMessage -->
        <test-method status="PASS" signature="closeBrowser()[pri:0, instance:tests.LoginTest@77fbd92c]" name="closeBrowser" is-config="true" duration-ms="800" started-at="2019-06-10T10:16:22Z" finished-at="2019-06-10T10:16:23Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
      </class> <!-- tests.LoginTest -->
    </test> <!-- Validate login functionality -->
    <test name="Validate Sign up functionality" duration-ms="101628" started-at="2019-06-10T10:16:23Z" finished-at="2019-06-10T10:18:05Z">
      <class name="tests.SignUpTest">
        <test-method status="PASS" signature="openBrowser()[pri:0, instance:tests.SignUpTest@5c6648b0]" name="openBrowser" is-config="true" duration-ms="4713" started-at="2019-06-10T10:16:23Z" finished-at="2019-06-10T10:16:28Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openBrowser -->
        <test-method status="FAIL" signature="verifyNotSamePasswordValidationMessage()[pri:1, instance:tests.SignUpTest@5c6648b0]" name="verifyNotSamePasswordValidationMessage" duration-ms="20718" started-at="2019-06-10T10:16:28Z" finished-at="2019-06-10T10:16:49Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Validation message is not showing for not same password on Repeat Password field  as per specification expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Validation message is not showing for not same password on Repeat Password field  as per specification expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at tests.SignUpTest.verifyNotSamePasswordValidationMessage(SignUpTest.java:44)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyNotSamePasswordValidationMessage -->
        <test-method status="PASS" signature="verifyInvalidPasswordFormatMessage()[pri:2, instance:tests.SignUpTest@5c6648b0]" name="verifyInvalidPasswordFormatMessage" duration-ms="73367" started-at="2019-06-10T10:16:49Z" finished-at="2019-06-10T10:18:02Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyInvalidPasswordFormatMessage -->
        <test-method status="PASS" signature="closeBrowser()[pri:0, instance:tests.SignUpTest@5c6648b0]" name="closeBrowser" is-config="true" duration-ms="2351" started-at="2019-06-10T10:18:02Z" finished-at="2019-06-10T10:18:05Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
      </class> <!-- tests.SignUpTest -->
    </test> <!-- Validate Sign up functionality -->
  </suite> <!-- Suite -->
</testng-results>
